public class DmlOperations {
    public static void dmlOperations()
    {
        // Insert
   /*     Account acc = new Account(Name='Tech School',Cities__c='Bangalore',Phone='1234455');
        insert acc;
        
        System.debug('accId = '+acc.id);
    */ 
     
      /*
        // Bulk Insert
        Account acc1 = new Account(Name='Tech School2',Cities__c='Bangalore',Phone='1234455');
        Account acc2 = new Account(Name='Tech School3',Cities__c='Bangalore',Phone='1234455');
        List<Account> accList = new List<Account>();
        accList.add(acc1);
        accList.add(acc2);
        insert accList;
        System.debug('accList = '+accList);
        
        */  
    }

}