public class OpportunityTriggerHandle {
	public static void handleActivitiesAfterInsert()
    {
        
    }
    
    /* public static void handleActivitiesAfterUpdate(List<Opportunity> newRecords)
    {
        // Whenever opp is closed Won,Create a Task for that Opp Owner to Splt the rRevenue among the team Priority
        for(Opportunity opp : newRecords)
        {
            if(opp.StageName == 'Closed Won')
            {
                
            }
        }
    }
*/
}